CHARACTER*30 ::  NOM1,NOM2
INTEGER*1    ::  DAT(2000000)
WRITE(*,*) ' INDICA NOMBRE DE ARCHIVO DE IMAGEN'
READ(*,*) NOM1
WRITE(*,*) ' INDICA NOMBRE DE ARCHIVO DE NEGATIVO'
READ(*,*) NOM2
WRITE(*,*) 'ESCRIBE TAMAÑO EN BYTES'
READ(*,*) NTAM
WRITE(*,*) 'INDICA LARGO DE IMAGEN EN PIXELES'
READ(*,*) NL
WRITE(*,*) 'INDICA ALTO DE IMAGEN EN PIXELES'
READ(*,*) NA
WRITE(*,*) 'INDICA NUMERO DE BYTES POR PIXEL'
READ(*,*) NPIX
OPEN(40,FILE=NOM1,ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='OLD',RECL=NTAM)
READ(40,REC=1)(DAT(I),I=1,NTAM)
NEN=NTAM-NL*NA*NPIX
OPEN(41,FILE=NOM2,ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='NEW',RECL=NTAM)
DO I=NEN+1,NTAM
DAT(I)=255-DAT(I)
ENDDO
WRITE(41,REC=1)(DAT(I),I=1,NTAM)
CLOSE (40)
CLOSE (41)
END

